# RAT-64 カーゴ設定ファイル
# ビルド最適化とキャッシュ設定

[build]
# 並列ビルドジョブ数（CPUコア数に合わせて調整）
jobs = 16

# リンカー最適化
[target.x86_64-pc-windows-msvc]
rustflags = [
  "-C", "link-arg=/OPT:REF",       # 未参照シンボル削除
  "-C", "link-arg=/OPT:ICF",       # 同一COMDAT折り畳み
  "-C", "target-cpu=native",       # ネイティブCPU最適化
]

# キャッシュディレクトリ設定（vendoringは手動設定時のみ有効）
# [source.crates-io]
# replace-with = "vendored-sources"

# [source.vendored-sources]
# directory = "vendor"

# プロファイル別最適化
[profile.dev]
split-debuginfo = "unpacked"  # デバッグ情報を高速化

[profile.release]
split-debuginfo = "off"       # リリース時はデバッグ情報なし